name: Manually create a release

on:

  workflow_dispatch:
    inputs:
      description:
        description: 'Short explanation of the release'
        required: true

env:
  IMAGE_NAME: integration-smpp

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
    - name: Setup release information
      run: |
        versionName=`sed '1q;d' versions.txt | cut -d "=" -f2 | xargs`
        export VERSION_NAME=$versionName
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        export NEXT_VERSION_NAME=$(echo ${VERSION_NAME} | awk -F. -v OFS=. '{$NF++;print}')
        echo "NEXT_VERSION_NAME=$NEXT_VERSION_NAME" >> $GITHUB_ENV
    - name: Change version number and name
      run: printf 'image_version = ${{ env.NEXT_VERSION_NAME }}\n' > versions.txt
    - name: Commit the version manifest files
      id: make-commit
      run: |
        git add versions.txt
        git commit --message "bump release version ${{ github.event.inputs.description }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Tag our release to freeze time
      id: make-release-tag
      run: |
        git tag -a v${{ env.VERSION_NAME }} -m "${{ github.event.inputs.description }}"
    - name: Push release tags
      run: git push origin v${{ env.VERSION_NAME }}

    - name: Setup jdk for compilation and docker release build version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Compile with Gradle
      run: ./gradlew jibDockerBuild --image=ghcr.io/${{ github.repository }}

    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: |

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')

        echo IMAGE_ID=$IMAGE_ID

        docker tag ghcr.io/${{ github.repository }} $IMAGE_ID:${{ github.sha }} $IMAGE_ID:v${{ env.VERSION_NAME }} $IMAGE_ID:latest

        docker push $IMAGE_ID:${{ github.sha }}

    - name: Print Full Image URL
      run: echo ghcr.io/${{ github.repository }}:${{ github.sha }}